<img src="Tarjeta.png">

# EJERCICIOS - NumPy Arrays

## Listas

1 - importa numpy como np y imprime la versión 


In [2]:
import numpy as np
print(np.__version__)

1.19.2


2 - Crea un array de numpy con valores de 0-9



In [8]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3 - Extrae todos los elementos impares del array anterior

In [16]:
array_imp = array[array % 2 != 0]
array_imp

array([1, 3, 5, 7, 9])

4 - Reemplaza todos los elementos impares del array anterior por -1 

In [17]:
array[array % 2 != 0] = -1
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

5 - Cambia la forma del array 1d a un array 2d con 2 filas

In [23]:
array.reshape([2, 5])

array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

6 - Dados dos arrays, 

a = np.array([1,2,3,2,3,4,3,4,5,6])


b = np.array([7,2,10,2,7,4,9,4,9,8])

comprueba los elementos repetidos entre ambos arrays

In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [31]:
a[a == b]

array([2, 2, 4, 4])

In [32]:
np.unique(a[a==b])

array([2, 4])

7 - Elimina de a los elementos que también contiene b



In [ ]:
# Dos formas de realizar este ejercicio:

In [33]:
a[a != b]

array([1, 3, 3, 3, 5, 6])

In [34]:
np.unique(a[a != b])

array([1, 3, 5, 6])

In [ ]:
# La otra forma

In [37]:
a[~ np.isin(a,b)]

array([1, 3, 3, 3, 5, 6])

In [38]:
np.unique(a[~ np.isin(a,b)])

array([1, 3, 5, 6])

8 - Devuelve posiciones de los elementos de a que son comunes con b

In [41]:
np.unique(a[a == b])

array([2, 4])

In [42]:
a

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [44]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

9 - Crea un array 3x3 con elementos del 0 al 8

In [54]:
arr = np.array(np.arange(9))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
mi_arr = arr.reshape([3,3])
mi_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10 - Intercambia de orden las columnas 1 y 2 del array 

In [63]:
col1 = mi_arr[:,1].copy()
col2 = mi_arr[:,2].copy()

In [65]:
mi_arr[:,1], mi_arr[:,2] = col2, col1
mi_arr

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

11 - Intercambia ahora las filas 2 y 3

In [66]:
raw1 = mi_arr[1,:].copy()
raw2 = mi_arr[2,:].copy()

In [68]:
mi_arr[1,:], mi_arr[2,:] = raw2, raw1
mi_arr

array([[0, 2, 1],
       [6, 8, 7],
       [3, 5, 4]])

12 - Calcula la media, el máximo, el mínimo y la desviación estandard de cada fila

In [71]:
mi_arr.mean(axis = 0) #media de cada columna

array([3., 5., 4.])

In [72]:
mi_arr.max(axis = 0) #max de cada columna

array([6, 8, 7])

In [73]:
mi_arr.min(axis = 0) #min de cada columna

array([0, 2, 1])

In [75]:
mi_arr.std(axis = 0) #desviación estandar de cada columna

array([2.44948974, 2.44948974, 2.44948974])

In [85]:
for i in range(mi_arr.shape[0]):
    print("fila ",i,": ",mi_arr[:,i],": media=",mi_arr[:,i].mean(), ", max=",mi_arr[:,i].max(),", min=",mi_arr[:,i].min(),", sdev=",round(mi_arr[:,i].std(),2))

fila  0 :  [0 6 3] : media= 3.0 , max= 6 , min= 0 , sdev= 2.45
fila  1 :  [2 8 5] : media= 5.0 , max= 8 , min= 2 , sdev= 2.45
fila  2 :  [1 7 4] : media= 4.0 , max= 7 , min= 1 , sdev= 2.45


13 - Suma los valores de cada columna

In [76]:
mi_arr.sum(axis = 0)

array([ 9, 15, 12])

In [86]:
for i in range(mi_arr.shape[1]):
    print("columna",i,": ",mi_arr[i,:],": suma=",mi_arr[i,:].sum())

columna 0 :  [0 2 1] : suma= 3
columna 1 :  [6 8 7] : suma= 21
columna 2 :  [3 5 4] : suma= 12


14 - ¿Hay algun elemento repetido en el array? 

In [95]:
elem_unicos, frecuencia = np.unique(mi_arr, return_counts=True)
frecuencia #Como ningún valores se repite, la frecuencia de todos los valores es 1

array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [94]:
if frecuencia[frecuencia != 1].size != 0:
    print('Hay valores repetidos')
else:
    print('No hay valores repetidos')


No hay valores repetidos


15 - Crea un array 2x3 de 0

In [99]:
arr_0 = np.zeros([2,3], dtype=int)
arr_0

array([[0, 0, 0],
       [0, 0, 0]])

16 - Crea un array 3x4 de números aleatorios y restale 1 a cada elemento de la matriz 

In [110]:
arr_al = np.random.random([3,4])
arr_al

array([[0.39434032, 0.19520249, 0.36988574, 0.81060741],
       [0.90485804, 0.52339432, 0.37951278, 0.2954183 ],
       [0.43867801, 0.3698274 , 0.036439  , 0.57824605]])

17 - Traspone el array anterior y sepáralo en 2 arrays 

In [111]:
arr_al_t = arr_al.T
arr_al_t

array([[0.39434032, 0.90485804, 0.43867801],
       [0.19520249, 0.52339432, 0.3698274 ],
       [0.36988574, 0.37951278, 0.036439  ],
       [0.81060741, 0.2954183 , 0.57824605]])

In [113]:
arr_a, arr_b = np.array_split(arr_al_t, 2)

In [114]:
arr_a

array([[0.39434032, 0.90485804, 0.43867801],
       [0.19520249, 0.52339432, 0.3698274 ]])

In [115]:
arr_b

array([[0.36988574, 0.37951278, 0.036439  ],
       [0.81060741, 0.2954183 , 0.57824605]])

18 - Eleva al cuadrado la matriz

In [116]:
arr_al_t ** 2

array([[0.15550429, 0.81876807, 0.1924384 ],
       [0.03810401, 0.27394161, 0.13677231],
       [0.13681546, 0.14402995, 0.0013278 ],
       [0.65708437, 0.08727197, 0.33436849]])

19 - Comprueba que multiplicar el siguiente array conformado por 1 da el mismo valor.

arr = [  [3,4,5]  ,  [6,8,9]   ,  [1,5,9]   ]


In [135]:
arr = [  [3,4,5]  ,  [6,8,9]   ,  [1,5,9]   ]
arr = np.array(arr)
arr

array([[3, 4, 5],
       [6, 8, 9],
       [1, 5, 9]])

In [138]:
np.multiply(arr, np.ones(arr.shape)) == arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

20 - Genera un array de valores aleatorios según distribución uniforme de 1-50, por steps de 20. Reemplaza los elementos superiores a 20  por 0

In [155]:
np.random.seed(100) #gracias a esta función, el random.uniform siempre dará los mismo valores. 
arr = np.random.uniform(1,50,8)
arr

array([ 7.69862289, 29.17957314, 44.67477576, 11.25090398, 10.08108276,
        6.31046763, 11.76517714, 48.95256545])

In [162]:
arr[np.where(arr > 20)] = 0
arr

array([ 7.69862289,  0.        ,  0.        , 11.25090398, 10.08108276,
        6.31046763, 11.76517714,  0.        ])